apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: mon-metric-loki
  labels:
    app.kubernetes.io/component: memcached-chunks-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 3.5.7
  name: loki-chunks-cache
  namespace: mon-metric-loki
spec:
  ports:
    - name: memcached-client
      port: 11211
      protocol: TCP
      targetPort: client
    - name: http-metrics
      port: 9150
      protocol: TCP
      targetPort: http-metrics
  selector:
    app.kubernetes.io/component: memcached-chunks-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: ClusterIP
